export const SEARCH_ITUNES_ACTION = 'SEARCH_ITUNES_ACTION'
export const SEARCH_ITUNES_ACTION_SUCCESS_ACTION  = 'SEARCH_ITUNES_ACTION_SUCCESS_ACTION'
export const SEARCH_ITUNES_ACTION_FAILURE_ACTION = 'SEARCH_ITUNES_ACTION_FAILURE_ACTION'