export const SEARCH_ITUNES_ACTION = 'SEARCH_ITUNES_ACTION'
export const SEARCH_ITUNES_SUCCESS_ACTION  = 'SEARCH_ITUNES_SUCCESS_ACTION'
export const SEARCH_ITUNES_FAILURE_ACTION = 'SEARCH_ITUNES_FAILURE_ACTION'
export const SEARCH_ITUNES_OFFLINE_ACTION = 'SEARCH_ITUNES_OFFLINE_ACTION'